name: Provision Fabric Data Platform
on: workflow_dispatch 
# on:
#   push:
#     branches:
#         - main
#     paths:
#         - '**.bicep'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - uses: actions/checkout@v3
    
    #Log into Azure
    - uses: azure/login@v1
      with:
           creds: '{"clientId":"${{ secrets.ACTION_SPN_CLIENTID }}","clientSecret":"${{ secrets.ACTION_SPN_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

    # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        region: australiaeast
        subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
        template: iac/bicep/main.bicep
        # parameters: 'k1=v1 k2=v2 k3=v3'
        # Note: The latest version of the Azure ARM Deploy action is azure/arm-deploy@v1.0.10, but this repository has been deprecated.
        # Microsoft recommends using azure/cli or azure/arm-deploy@v1 (which points to the latest v1 release).
        # Reference: https://github.com/Azure/arm-deploy

        # To use the latest stable version, update the uses line to:
        # uses: azure/arm-deploy@v1
